### ISSUE TITLE
Organisms move towards left more likely than other directions

### ISSUE THREAD

**Issue by emilio-molina** [EliosMolina/ecosystem#1]

**Comment by salasgar** [comment]
Se mueven y/o comen con más frecuencia hacia la izquierda

**Comment by emilio-molina** [comment]
Me lo asigno yo.

**Comment by emilio-molina** [comment]
@salasgar Estoy intentando reproducir el problema pero no lo consigo. Me puedes decir exactamente qué es lo que has observado?

**Comment by emilio-molina** [comment]
Ah ya lo he encontrado y lo he integrado con pull request #10. Creo que los movimientos sí son aleatorios, pero el hunting no. Ahora los dos son aleatorios.

Si más adelante volvemos a encontrar problemas abrimos otro issue.
