### ISSUE TITLE
Add mutation functionality

### ISSUE THREAD

**Issue by emilio-molina** [EliosMolina/ecosystem#3]

**Comment by salasgar** [comment]
Tal y como está, al añadir mutabilidad los organismos mejorarán sus capacidades indefinidamente (aumentarán su probabilidad de procrear, su longevidad, etc...) y se convertirán en superbichos. Esto no es natural.
Para que esto no ocurra, hay que ponerles alguna contrapartida. Cuando usábamos la variable "energy reserve", la contrapartida solía ser un aumento exponencial del gasto energético, lo cual les obligaba a situarse en niveles "normales" y no convertirse en superbichos. Esta, de hecho, es una contrapartida muy frecuente en la naturaleza.
Al no haber implementado el tema de la energía, la contrapartida que voy a poner es que, sumando la probabilidad de procrear (en tanto por ciento) más la longevidad más la capacidad de ataque más la capacidad de defensa no puede dar más de 100. A ver cómo se las apañan.

**Comment by emilio-molina** [comment]
Really needed? Closed by the moment.
