### ISSUE TITLE
Experiments are too heavy for being in the repository

### ISSUE THREAD

**Issue by emilio-molina** [EliosMolina/ecosystem#5]
# Tamaño de los experimentos de test en el repositorio

114M ./test5
75M ./test3
90M ./test4
10M ./test

Son demasiado pesados, y el repositorio tiene un límite de tamaño limitado (creo 1GB). Yo en el repositorio tendría algunos experimentos de test pequeños, sólo para probar funcionalidades de la GUI, y el resto los tendría en otro sitio (e.g. dropbox?). O bien los almacenaría en local y los iría enviando por wetransfer si ocupan mucho (e.g. >300MB). 
# Ideas para reducir tamaño
- Exportar cada time slice en formato binario optimizado a nivel de bit, en lugar de un JSON que tiene mucho overhead por ser cadenas de caracteres.
- Utilizar compresión ZIP (llamando al comando 'zip' en commandline) para cada time slice. Creo que se puede ir descomprimiento a tiempo real en la GUI y no supondría mucho tiempo. Utilizando compresión ZIP he comprobado que test5 pasa de 114M a 25M.

Creo que estas dos ideas, podemos reducir >75% el tamaño de los experimentos.

**Comment by salasgar** [comment]
También podemos guardar un array en lugar de un diccionario

**Comment by emilio-molina** [comment]
Ahora aplica z compression a los fichero .json.
